// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: subjects/subject_message.proto

package subjects

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	generic "lms-class-service/pb/generic"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Subject struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UniversityId    string                 `protobuf:"bytes,2,opt,name=university_id,json=universityId,proto3" json:"university_id,omitempty"`
	UniversityName  string                 `protobuf:"bytes,3,opt,name=university_name,json=universityName,proto3" json:"university_name,omitempty"`
	FacultyId       string                 `protobuf:"bytes,4,opt,name=faculty_id,json=facultyId,proto3" json:"faculty_id,omitempty"`
	FacultyName     string                 `protobuf:"bytes,5,opt,name=faculty_name,json=facultyName,proto3" json:"faculty_name,omitempty"`
	ProgrammeId     string                 `protobuf:"bytes,6,opt,name=programme_id,json=programmeId,proto3" json:"programme_id,omitempty"`
	ProgrammeName   string                 `protobuf:"bytes,7,opt,name=programme_name,json=programmeName,proto3" json:"programme_name,omitempty"`
	Code            string                 `protobuf:"bytes,8,opt,name=code,proto3" json:"code,omitempty"`
	Name            string                 `protobuf:"bytes,9,opt,name=name,proto3" json:"name,omitempty"`
	Sks             int32                  `protobuf:"varint,10,opt,name=sks,proto3" json:"sks,omitempty"`
	DefaultSemester int32                  `protobuf:"varint,11,opt,name=default_semester,json=defaultSemester,proto3" json:"default_semester,omitempty"`
	UpdatedBy       string                 `protobuf:"bytes,12,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	UpdatedAt       string                 `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Topics          []*TopicSubject        `protobuf:"bytes,15,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Subject) Reset() {
	*x = Subject{}
	mi := &file_subjects_subject_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subject) ProtoMessage() {}

func (x *Subject) ProtoReflect() protoreflect.Message {
	mi := &file_subjects_subject_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subject.ProtoReflect.Descriptor instead.
func (*Subject) Descriptor() ([]byte, []int) {
	return file_subjects_subject_message_proto_rawDescGZIP(), []int{0}
}

func (x *Subject) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Subject) GetUniversityId() string {
	if x != nil {
		return x.UniversityId
	}
	return ""
}

func (x *Subject) GetUniversityName() string {
	if x != nil {
		return x.UniversityName
	}
	return ""
}

func (x *Subject) GetFacultyId() string {
	if x != nil {
		return x.FacultyId
	}
	return ""
}

func (x *Subject) GetFacultyName() string {
	if x != nil {
		return x.FacultyName
	}
	return ""
}

func (x *Subject) GetProgrammeId() string {
	if x != nil {
		return x.ProgrammeId
	}
	return ""
}

func (x *Subject) GetProgrammeName() string {
	if x != nil {
		return x.ProgrammeName
	}
	return ""
}

func (x *Subject) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Subject) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Subject) GetSks() int32 {
	if x != nil {
		return x.Sks
	}
	return 0
}

func (x *Subject) GetDefaultSemester() int32 {
	if x != nil {
		return x.DefaultSemester
	}
	return 0
}

func (x *Subject) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *Subject) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Subject) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Subject) GetTopics() []*TopicSubject {
	if x != nil {
		return x.Topics
	}
	return nil
}

type TopicSubject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SubjectId     string                 `protobuf:"bytes,2,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,4,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicSubject) Reset() {
	*x = TopicSubject{}
	mi := &file_subjects_subject_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicSubject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicSubject) ProtoMessage() {}

func (x *TopicSubject) ProtoReflect() protoreflect.Message {
	mi := &file_subjects_subject_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicSubject.ProtoReflect.Descriptor instead.
func (*TopicSubject) Descriptor() ([]byte, []int) {
	return file_subjects_subject_message_proto_rawDescGZIP(), []int{1}
}

func (x *TopicSubject) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TopicSubject) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *TopicSubject) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TopicSubject) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *TopicSubject) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *TopicSubject) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type SubjectList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subjects      []*Subject             `protobuf:"bytes,1,rep,name=subjects,proto3" json:"subjects,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubjectList) Reset() {
	*x = SubjectList{}
	mi := &file_subjects_subject_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubjectList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubjectList) ProtoMessage() {}

func (x *SubjectList) ProtoReflect() protoreflect.Message {
	mi := &file_subjects_subject_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubjectList.ProtoReflect.Descriptor instead.
func (*SubjectList) Descriptor() ([]byte, []int) {
	return file_subjects_subject_message_proto_rawDescGZIP(), []int{2}
}

func (x *SubjectList) GetSubjects() []*Subject {
	if x != nil {
		return x.Subjects
	}
	return nil
}

func (x *SubjectList) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type SubjectListInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *generic.Pagination    `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubjectListInput) Reset() {
	*x = SubjectListInput{}
	mi := &file_subjects_subject_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubjectListInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubjectListInput) ProtoMessage() {}

func (x *SubjectListInput) ProtoReflect() protoreflect.Message {
	mi := &file_subjects_subject_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubjectListInput.ProtoReflect.Descriptor instead.
func (*SubjectListInput) Descriptor() ([]byte, []int) {
	return file_subjects_subject_message_proto_rawDescGZIP(), []int{3}
}

func (x *SubjectListInput) GetPagination() *generic.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type SubjectInput struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UniversityId    string                 `protobuf:"bytes,1,opt,name=university_id,json=universityId,proto3" json:"university_id,omitempty"`
	UniversityName  string                 `protobuf:"bytes,2,opt,name=university_name,json=universityName,proto3" json:"university_name,omitempty"`
	FacultyId       string                 `protobuf:"bytes,3,opt,name=faculty_id,json=facultyId,proto3" json:"faculty_id,omitempty"`
	FacultyName     string                 `protobuf:"bytes,4,opt,name=faculty_name,json=facultyName,proto3" json:"faculty_name,omitempty"`
	ProgrammeId     string                 `protobuf:"bytes,5,opt,name=programme_id,json=programmeId,proto3" json:"programme_id,omitempty"`
	ProgrammeName   string                 `protobuf:"bytes,6,opt,name=programme_name,json=programmeName,proto3" json:"programme_name,omitempty"`
	Code            string                 `protobuf:"bytes,7,opt,name=code,proto3" json:"code,omitempty"`
	Name            string                 `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	Sks             int32                  `protobuf:"varint,9,opt,name=sks,proto3" json:"sks,omitempty"`
	DefaultSemester int32                  `protobuf:"varint,10,opt,name=default_semester,json=defaultSemester,proto3" json:"default_semester,omitempty"`
	Topics          []*TopicSubjectInput   `protobuf:"bytes,11,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SubjectInput) Reset() {
	*x = SubjectInput{}
	mi := &file_subjects_subject_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubjectInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubjectInput) ProtoMessage() {}

func (x *SubjectInput) ProtoReflect() protoreflect.Message {
	mi := &file_subjects_subject_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubjectInput.ProtoReflect.Descriptor instead.
func (*SubjectInput) Descriptor() ([]byte, []int) {
	return file_subjects_subject_message_proto_rawDescGZIP(), []int{4}
}

func (x *SubjectInput) GetUniversityId() string {
	if x != nil {
		return x.UniversityId
	}
	return ""
}

func (x *SubjectInput) GetUniversityName() string {
	if x != nil {
		return x.UniversityName
	}
	return ""
}

func (x *SubjectInput) GetFacultyId() string {
	if x != nil {
		return x.FacultyId
	}
	return ""
}

func (x *SubjectInput) GetFacultyName() string {
	if x != nil {
		return x.FacultyName
	}
	return ""
}

func (x *SubjectInput) GetProgrammeId() string {
	if x != nil {
		return x.ProgrammeId
	}
	return ""
}

func (x *SubjectInput) GetProgrammeName() string {
	if x != nil {
		return x.ProgrammeName
	}
	return ""
}

func (x *SubjectInput) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *SubjectInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SubjectInput) GetSks() int32 {
	if x != nil {
		return x.Sks
	}
	return 0
}

func (x *SubjectInput) GetDefaultSemester() int32 {
	if x != nil {
		return x.DefaultSemester
	}
	return 0
}

func (x *SubjectInput) GetTopics() []*TopicSubjectInput {
	if x != nil {
		return x.Topics
	}
	return nil
}

type TopicSubjectInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicSubjectInput) Reset() {
	*x = TopicSubjectInput{}
	mi := &file_subjects_subject_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicSubjectInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicSubjectInput) ProtoMessage() {}

func (x *TopicSubjectInput) ProtoReflect() protoreflect.Message {
	mi := &file_subjects_subject_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicSubjectInput.ProtoReflect.Descriptor instead.
func (*TopicSubjectInput) Descriptor() ([]byte, []int) {
	return file_subjects_subject_message_proto_rawDescGZIP(), []int{5}
}

func (x *TopicSubjectInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_subjects_subject_message_proto protoreflect.FileDescriptor

const file_subjects_subject_message_proto_rawDesc = "" +
	"\n" +
	"\x1esubjects/subject_message.proto\x12\bsubjects\x1a\x1dgeneric/generic_message.proto\"\xe5\x03\n" +
	"\aSubject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\runiversity_id\x18\x02 \x01(\tR\funiversityId\x12'\n" +
	"\x0funiversity_name\x18\x03 \x01(\tR\x0euniversityName\x12\x1d\n" +
	"\n" +
	"faculty_id\x18\x04 \x01(\tR\tfacultyId\x12!\n" +
	"\ffaculty_name\x18\x05 \x01(\tR\vfacultyName\x12!\n" +
	"\fprogramme_id\x18\x06 \x01(\tR\vprogrammeId\x12%\n" +
	"\x0eprogramme_name\x18\a \x01(\tR\rprogrammeName\x12\x12\n" +
	"\x04code\x18\b \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\t \x01(\tR\x04name\x12\x10\n" +
	"\x03sks\x18\n" +
	" \x01(\x05R\x03sks\x12)\n" +
	"\x10default_semester\x18\v \x01(\x05R\x0fdefaultSemester\x12\x1d\n" +
	"\n" +
	"updated_by\x18\f \x01(\tR\tupdatedBy\x12\x1d\n" +
	"\n" +
	"updated_at\x18\r \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0e \x01(\tR\tcreatedAt\x12.\n" +
	"\x06topics\x18\x0f \x03(\v2\x16.subjects.TopicSubjectR\x06topics\"\xae\x01\n" +
	"\fTopicSubject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x02 \x01(\tR\tsubjectId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"updated_by\x18\x04 \x01(\tR\tupdatedBy\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\"R\n" +
	"\vSubjectList\x12-\n" +
	"\bsubjects\x18\x01 \x03(\v2\x11.subjects.SubjectR\bsubjects\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\"R\n" +
	"\x10SubjectListInput\x12>\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x1e.lms_class_services.PaginationR\n" +
	"pagination\"\x82\x03\n" +
	"\fSubjectInput\x12#\n" +
	"\runiversity_id\x18\x01 \x01(\tR\funiversityId\x12'\n" +
	"\x0funiversity_name\x18\x02 \x01(\tR\x0euniversityName\x12\x1d\n" +
	"\n" +
	"faculty_id\x18\x03 \x01(\tR\tfacultyId\x12!\n" +
	"\ffaculty_name\x18\x04 \x01(\tR\vfacultyName\x12!\n" +
	"\fprogramme_id\x18\x05 \x01(\tR\vprogrammeId\x12%\n" +
	"\x0eprogramme_name\x18\x06 \x01(\tR\rprogrammeName\x12\x12\n" +
	"\x04code\x18\a \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\b \x01(\tR\x04name\x12\x10\n" +
	"\x03sks\x18\t \x01(\x05R\x03sks\x12)\n" +
	"\x10default_semester\x18\n" +
	" \x01(\x05R\x0fdefaultSemester\x123\n" +
	"\x06topics\x18\v \x03(\v2\x1b.subjects.TopicSubjectInputR\x06topics\"'\n" +
	"\x11TopicSubjectInput\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name2\xa5\x02\n" +
	"\x0eSubjectService\x129\n" +
	"\x04List\x12\x1a.subjects.SubjectListInput\x1a\x15.subjects.SubjectList\x120\n" +
	"\x03Get\x12\x16.lms_class_services.Id\x1a\x11.subjects.Subject\x123\n" +
	"\x06Create\x12\x16.subjects.SubjectInput\x1a\x11.subjects.Subject\x12.\n" +
	"\x06Update\x12\x11.subjects.Subject\x1a\x11.subjects.Subject\x12A\n" +
	"\x06Delete\x12\x16.lms_class_services.Id\x1a\x1f.lms_class_services.BoolMessageB(Z&lms-class-service/pb/subjects;subjectsb\x06proto3"

var (
	file_subjects_subject_message_proto_rawDescOnce sync.Once
	file_subjects_subject_message_proto_rawDescData []byte
)

func file_subjects_subject_message_proto_rawDescGZIP() []byte {
	file_subjects_subject_message_proto_rawDescOnce.Do(func() {
		file_subjects_subject_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_subjects_subject_message_proto_rawDesc), len(file_subjects_subject_message_proto_rawDesc)))
	})
	return file_subjects_subject_message_proto_rawDescData
}

var file_subjects_subject_message_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_subjects_subject_message_proto_goTypes = []any{
	(*Subject)(nil),             // 0: subjects.Subject
	(*TopicSubject)(nil),        // 1: subjects.TopicSubject
	(*SubjectList)(nil),         // 2: subjects.SubjectList
	(*SubjectListInput)(nil),    // 3: subjects.SubjectListInput
	(*SubjectInput)(nil),        // 4: subjects.SubjectInput
	(*TopicSubjectInput)(nil),   // 5: subjects.TopicSubjectInput
	(*generic.Pagination)(nil),  // 6: lms_class_services.Pagination
	(*generic.Id)(nil),          // 7: lms_class_services.Id
	(*generic.BoolMessage)(nil), // 8: lms_class_services.BoolMessage
}
var file_subjects_subject_message_proto_depIdxs = []int32{
	1, // 0: subjects.Subject.topics:type_name -> subjects.TopicSubject
	0, // 1: subjects.SubjectList.subjects:type_name -> subjects.Subject
	6, // 2: subjects.SubjectListInput.pagination:type_name -> lms_class_services.Pagination
	5, // 3: subjects.SubjectInput.topics:type_name -> subjects.TopicSubjectInput
	3, // 4: subjects.SubjectService.List:input_type -> subjects.SubjectListInput
	7, // 5: subjects.SubjectService.Get:input_type -> lms_class_services.Id
	4, // 6: subjects.SubjectService.Create:input_type -> subjects.SubjectInput
	0, // 7: subjects.SubjectService.Update:input_type -> subjects.Subject
	7, // 8: subjects.SubjectService.Delete:input_type -> lms_class_services.Id
	2, // 9: subjects.SubjectService.List:output_type -> subjects.SubjectList
	0, // 10: subjects.SubjectService.Get:output_type -> subjects.Subject
	0, // 11: subjects.SubjectService.Create:output_type -> subjects.Subject
	0, // 12: subjects.SubjectService.Update:output_type -> subjects.Subject
	8, // 13: subjects.SubjectService.Delete:output_type -> lms_class_services.BoolMessage
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_subjects_subject_message_proto_init() }
func file_subjects_subject_message_proto_init() {
	if File_subjects_subject_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_subjects_subject_message_proto_rawDesc), len(file_subjects_subject_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_subjects_subject_message_proto_goTypes,
		DependencyIndexes: file_subjects_subject_message_proto_depIdxs,
		MessageInfos:      file_subjects_subject_message_proto_msgTypes,
	}.Build()
	File_subjects_subject_message_proto = out.File
	file_subjects_subject_message_proto_goTypes = nil
	file_subjects_subject_message_proto_depIdxs = nil
}
