// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.1
// source: classes/class_message.proto

package classes

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	generic "lms-class-service/pb/generic"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClassService_List_FullMethodName   = "/classes.ClassService/List"
	ClassService_Get_FullMethodName    = "/classes.ClassService/Get"
	ClassService_Create_FullMethodName = "/classes.ClassService/Create"
	ClassService_Update_FullMethodName = "/classes.ClassService/Update"
	ClassService_Delete_FullMethodName = "/classes.ClassService/Delete"
)

// ClassServiceClient is the client API for ClassService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClassServiceClient interface {
	List(ctx context.Context, in *ClassListInput, opts ...grpc.CallOption) (*ClassList, error)
	Get(ctx context.Context, in *generic.Id, opts ...grpc.CallOption) (*Class, error)
	Create(ctx context.Context, in *ClassInput, opts ...grpc.CallOption) (*Class, error)
	Update(ctx context.Context, in *Class, opts ...grpc.CallOption) (*Class, error)
	Delete(ctx context.Context, in *generic.Id, opts ...grpc.CallOption) (*generic.BoolMessage, error)
}

type classServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClassServiceClient(cc grpc.ClientConnInterface) ClassServiceClient {
	return &classServiceClient{cc}
}

func (c *classServiceClient) List(ctx context.Context, in *ClassListInput, opts ...grpc.CallOption) (*ClassList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClassList)
	err := c.cc.Invoke(ctx, ClassService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *classServiceClient) Get(ctx context.Context, in *generic.Id, opts ...grpc.CallOption) (*Class, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Class)
	err := c.cc.Invoke(ctx, ClassService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *classServiceClient) Create(ctx context.Context, in *ClassInput, opts ...grpc.CallOption) (*Class, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Class)
	err := c.cc.Invoke(ctx, ClassService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *classServiceClient) Update(ctx context.Context, in *Class, opts ...grpc.CallOption) (*Class, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Class)
	err := c.cc.Invoke(ctx, ClassService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *classServiceClient) Delete(ctx context.Context, in *generic.Id, opts ...grpc.CallOption) (*generic.BoolMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(generic.BoolMessage)
	err := c.cc.Invoke(ctx, ClassService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClassServiceServer is the server API for ClassService service.
// All implementations should embed UnimplementedClassServiceServer
// for forward compatibility.
type ClassServiceServer interface {
	List(context.Context, *ClassListInput) (*ClassList, error)
	Get(context.Context, *generic.Id) (*Class, error)
	Create(context.Context, *ClassInput) (*Class, error)
	Update(context.Context, *Class) (*Class, error)
	Delete(context.Context, *generic.Id) (*generic.BoolMessage, error)
}

// UnimplementedClassServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClassServiceServer struct{}

func (UnimplementedClassServiceServer) List(context.Context, *ClassListInput) (*ClassList, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedClassServiceServer) Get(context.Context, *generic.Id) (*Class, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedClassServiceServer) Create(context.Context, *ClassInput) (*Class, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedClassServiceServer) Update(context.Context, *Class) (*Class, error) {
	return nil, status.Error(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedClassServiceServer) Delete(context.Context, *generic.Id) (*generic.BoolMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedClassServiceServer) testEmbeddedByValue() {}

// UnsafeClassServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClassServiceServer will
// result in compilation errors.
type UnsafeClassServiceServer interface {
	mustEmbedUnimplementedClassServiceServer()
}

func RegisterClassServiceServer(s grpc.ServiceRegistrar, srv ClassServiceServer) {
	// If the following call panics, it indicates UnimplementedClassServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClassService_ServiceDesc, srv)
}

func _ClassService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClassListInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClassService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassServiceServer).List(ctx, req.(*ClassListInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClassService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(generic.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClassService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassServiceServer).Get(ctx, req.(*generic.Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClassService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClassInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClassService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassServiceServer).Create(ctx, req.(*ClassInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClassService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Class)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClassService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassServiceServer).Update(ctx, req.(*Class))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClassService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(generic.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClassService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassServiceServer).Delete(ctx, req.(*generic.Id))
	}
	return interceptor(ctx, in, info, handler)
}

// ClassService_ServiceDesc is the grpc.ServiceDesc for ClassService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClassService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "classes.ClassService",
	HandlerType: (*ClassServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _ClassService_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _ClassService_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _ClassService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ClassService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ClassService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "classes/class_message.proto",
}

const (
	SubjectClassService_List_FullMethodName   = "/classes.SubjectClassService/List"
	SubjectClassService_Get_FullMethodName    = "/classes.SubjectClassService/Get"
	SubjectClassService_Create_FullMethodName = "/classes.SubjectClassService/Create"
	SubjectClassService_Update_FullMethodName = "/classes.SubjectClassService/Update"
	SubjectClassService_Delete_FullMethodName = "/classes.SubjectClassService/Delete"
)

// SubjectClassServiceClient is the client API for SubjectClassService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SubjectClassServiceClient interface {
	List(ctx context.Context, in *SubjectClassListInput, opts ...grpc.CallOption) (*SubjectClassList, error)
	Get(ctx context.Context, in *generic.Id, opts ...grpc.CallOption) (*SubjectClass, error)
	Create(ctx context.Context, in *SubjectClassInput, opts ...grpc.CallOption) (*SubjectClass, error)
	Update(ctx context.Context, in *SubjectClass, opts ...grpc.CallOption) (*SubjectClass, error)
	Delete(ctx context.Context, in *generic.Id, opts ...grpc.CallOption) (*generic.BoolMessage, error)
}

type subjectClassServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSubjectClassServiceClient(cc grpc.ClientConnInterface) SubjectClassServiceClient {
	return &subjectClassServiceClient{cc}
}

func (c *subjectClassServiceClient) List(ctx context.Context, in *SubjectClassListInput, opts ...grpc.CallOption) (*SubjectClassList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubjectClassList)
	err := c.cc.Invoke(ctx, SubjectClassService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subjectClassServiceClient) Get(ctx context.Context, in *generic.Id, opts ...grpc.CallOption) (*SubjectClass, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubjectClass)
	err := c.cc.Invoke(ctx, SubjectClassService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subjectClassServiceClient) Create(ctx context.Context, in *SubjectClassInput, opts ...grpc.CallOption) (*SubjectClass, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubjectClass)
	err := c.cc.Invoke(ctx, SubjectClassService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subjectClassServiceClient) Update(ctx context.Context, in *SubjectClass, opts ...grpc.CallOption) (*SubjectClass, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubjectClass)
	err := c.cc.Invoke(ctx, SubjectClassService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subjectClassServiceClient) Delete(ctx context.Context, in *generic.Id, opts ...grpc.CallOption) (*generic.BoolMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(generic.BoolMessage)
	err := c.cc.Invoke(ctx, SubjectClassService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubjectClassServiceServer is the server API for SubjectClassService service.
// All implementations should embed UnimplementedSubjectClassServiceServer
// for forward compatibility.
type SubjectClassServiceServer interface {
	List(context.Context, *SubjectClassListInput) (*SubjectClassList, error)
	Get(context.Context, *generic.Id) (*SubjectClass, error)
	Create(context.Context, *SubjectClassInput) (*SubjectClass, error)
	Update(context.Context, *SubjectClass) (*SubjectClass, error)
	Delete(context.Context, *generic.Id) (*generic.BoolMessage, error)
}

// UnimplementedSubjectClassServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSubjectClassServiceServer struct{}

func (UnimplementedSubjectClassServiceServer) List(context.Context, *SubjectClassListInput) (*SubjectClassList, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedSubjectClassServiceServer) Get(context.Context, *generic.Id) (*SubjectClass, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedSubjectClassServiceServer) Create(context.Context, *SubjectClassInput) (*SubjectClass, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedSubjectClassServiceServer) Update(context.Context, *SubjectClass) (*SubjectClass, error) {
	return nil, status.Error(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedSubjectClassServiceServer) Delete(context.Context, *generic.Id) (*generic.BoolMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedSubjectClassServiceServer) testEmbeddedByValue() {}

// UnsafeSubjectClassServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SubjectClassServiceServer will
// result in compilation errors.
type UnsafeSubjectClassServiceServer interface {
	mustEmbedUnimplementedSubjectClassServiceServer()
}

func RegisterSubjectClassServiceServer(s grpc.ServiceRegistrar, srv SubjectClassServiceServer) {
	// If the following call panics, it indicates UnimplementedSubjectClassServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SubjectClassService_ServiceDesc, srv)
}

func _SubjectClassService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubjectClassListInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubjectClassServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubjectClassService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubjectClassServiceServer).List(ctx, req.(*SubjectClassListInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubjectClassService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(generic.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubjectClassServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubjectClassService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubjectClassServiceServer).Get(ctx, req.(*generic.Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubjectClassService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubjectClassInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubjectClassServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubjectClassService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubjectClassServiceServer).Create(ctx, req.(*SubjectClassInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubjectClassService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubjectClass)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubjectClassServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubjectClassService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubjectClassServiceServer).Update(ctx, req.(*SubjectClass))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubjectClassService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(generic.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubjectClassServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubjectClassService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubjectClassServiceServer).Delete(ctx, req.(*generic.Id))
	}
	return interceptor(ctx, in, info, handler)
}

// SubjectClassService_ServiceDesc is the grpc.ServiceDesc for SubjectClassService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SubjectClassService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "classes.SubjectClassService",
	HandlerType: (*SubjectClassServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _SubjectClassService_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _SubjectClassService_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _SubjectClassService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _SubjectClassService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _SubjectClassService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "classes/class_message.proto",
}

const (
	StudentClassService_List_FullMethodName   = "/classes.StudentClassService/List"
	StudentClassService_Get_FullMethodName    = "/classes.StudentClassService/Get"
	StudentClassService_Create_FullMethodName = "/classes.StudentClassService/Create"
	StudentClassService_Delete_FullMethodName = "/classes.StudentClassService/Delete"
)

// StudentClassServiceClient is the client API for StudentClassService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StudentClassServiceClient interface {
	List(ctx context.Context, in *StudentClassListInput, opts ...grpc.CallOption) (*StudentClassList, error)
	Get(ctx context.Context, in *generic.Id, opts ...grpc.CallOption) (*StudentClass, error)
	Create(ctx context.Context, in *StudentClassInput, opts ...grpc.CallOption) (*StudentClass, error)
	Delete(ctx context.Context, in *generic.Id, opts ...grpc.CallOption) (*generic.BoolMessage, error)
}

type studentClassServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStudentClassServiceClient(cc grpc.ClientConnInterface) StudentClassServiceClient {
	return &studentClassServiceClient{cc}
}

func (c *studentClassServiceClient) List(ctx context.Context, in *StudentClassListInput, opts ...grpc.CallOption) (*StudentClassList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StudentClassList)
	err := c.cc.Invoke(ctx, StudentClassService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studentClassServiceClient) Get(ctx context.Context, in *generic.Id, opts ...grpc.CallOption) (*StudentClass, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StudentClass)
	err := c.cc.Invoke(ctx, StudentClassService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studentClassServiceClient) Create(ctx context.Context, in *StudentClassInput, opts ...grpc.CallOption) (*StudentClass, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StudentClass)
	err := c.cc.Invoke(ctx, StudentClassService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studentClassServiceClient) Delete(ctx context.Context, in *generic.Id, opts ...grpc.CallOption) (*generic.BoolMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(generic.BoolMessage)
	err := c.cc.Invoke(ctx, StudentClassService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StudentClassServiceServer is the server API for StudentClassService service.
// All implementations should embed UnimplementedStudentClassServiceServer
// for forward compatibility.
type StudentClassServiceServer interface {
	List(context.Context, *StudentClassListInput) (*StudentClassList, error)
	Get(context.Context, *generic.Id) (*StudentClass, error)
	Create(context.Context, *StudentClassInput) (*StudentClass, error)
	Delete(context.Context, *generic.Id) (*generic.BoolMessage, error)
}

// UnimplementedStudentClassServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStudentClassServiceServer struct{}

func (UnimplementedStudentClassServiceServer) List(context.Context, *StudentClassListInput) (*StudentClassList, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedStudentClassServiceServer) Get(context.Context, *generic.Id) (*StudentClass, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedStudentClassServiceServer) Create(context.Context, *StudentClassInput) (*StudentClass, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedStudentClassServiceServer) Delete(context.Context, *generic.Id) (*generic.BoolMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedStudentClassServiceServer) testEmbeddedByValue() {}

// UnsafeStudentClassServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StudentClassServiceServer will
// result in compilation errors.
type UnsafeStudentClassServiceServer interface {
	mustEmbedUnimplementedStudentClassServiceServer()
}

func RegisterStudentClassServiceServer(s grpc.ServiceRegistrar, srv StudentClassServiceServer) {
	// If the following call panics, it indicates UnimplementedStudentClassServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StudentClassService_ServiceDesc, srv)
}

func _StudentClassService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StudentClassListInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentClassServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudentClassService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentClassServiceServer).List(ctx, req.(*StudentClassListInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudentClassService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(generic.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentClassServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudentClassService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentClassServiceServer).Get(ctx, req.(*generic.Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudentClassService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StudentClassInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentClassServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudentClassService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentClassServiceServer).Create(ctx, req.(*StudentClassInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudentClassService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(generic.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentClassServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudentClassService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentClassServiceServer).Delete(ctx, req.(*generic.Id))
	}
	return interceptor(ctx, in, info, handler)
}

// StudentClassService_ServiceDesc is the grpc.ServiceDesc for StudentClassService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StudentClassService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "classes.StudentClassService",
	HandlerType: (*StudentClassServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _StudentClassService_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _StudentClassService_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _StudentClassService_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _StudentClassService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "classes/class_message.proto",
}
