// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: classes/class_message.proto

package classes

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	generic "lms-class-service/pb/generic"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Class struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UniversityId   string                 `protobuf:"bytes,2,opt,name=university_id,json=universityId,proto3" json:"university_id,omitempty"`
	UniversityName string                 `protobuf:"bytes,3,opt,name=university_name,json=universityName,proto3" json:"university_name,omitempty"`
	FacultyId      string                 `protobuf:"bytes,4,opt,name=faculty_id,json=facultyId,proto3" json:"faculty_id,omitempty"`
	FacultyName    string                 `protobuf:"bytes,5,opt,name=faculty_name,json=facultyName,proto3" json:"faculty_name,omitempty"`
	ProgrammeId    string                 `protobuf:"bytes,6,opt,name=programme_id,json=programmeId,proto3" json:"programme_id,omitempty"`
	ProgrammeName  string                 `protobuf:"bytes,7,opt,name=programme_name,json=programmeName,proto3" json:"programme_name,omitempty"`
	Code           string                 `protobuf:"bytes,8,opt,name=code,proto3" json:"code,omitempty"`
	Name           string                 `protobuf:"bytes,9,opt,name=name,proto3" json:"name,omitempty"`
	UpdatedBy      string                 `protobuf:"bytes,10,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Class) Reset() {
	*x = Class{}
	mi := &file_classes_class_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Class) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Class) ProtoMessage() {}

func (x *Class) ProtoReflect() protoreflect.Message {
	mi := &file_classes_class_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Class.ProtoReflect.Descriptor instead.
func (*Class) Descriptor() ([]byte, []int) {
	return file_classes_class_message_proto_rawDescGZIP(), []int{0}
}

func (x *Class) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Class) GetUniversityId() string {
	if x != nil {
		return x.UniversityId
	}
	return ""
}

func (x *Class) GetUniversityName() string {
	if x != nil {
		return x.UniversityName
	}
	return ""
}

func (x *Class) GetFacultyId() string {
	if x != nil {
		return x.FacultyId
	}
	return ""
}

func (x *Class) GetFacultyName() string {
	if x != nil {
		return x.FacultyName
	}
	return ""
}

func (x *Class) GetProgrammeId() string {
	if x != nil {
		return x.ProgrammeId
	}
	return ""
}

func (x *Class) GetProgrammeName() string {
	if x != nil {
		return x.ProgrammeName
	}
	return ""
}

func (x *Class) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Class) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Class) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *Class) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Class) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ClassList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Classes       []*Class               `protobuf:"bytes,1,rep,name=classes,proto3" json:"classes,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassList) Reset() {
	*x = ClassList{}
	mi := &file_classes_class_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassList) ProtoMessage() {}

func (x *ClassList) ProtoReflect() protoreflect.Message {
	mi := &file_classes_class_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassList.ProtoReflect.Descriptor instead.
func (*ClassList) Descriptor() ([]byte, []int) {
	return file_classes_class_message_proto_rawDescGZIP(), []int{1}
}

func (x *ClassList) GetClasses() []*Class {
	if x != nil {
		return x.Classes
	}
	return nil
}

func (x *ClassList) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ClassListInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *generic.Pagination    `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassListInput) Reset() {
	*x = ClassListInput{}
	mi := &file_classes_class_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassListInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassListInput) ProtoMessage() {}

func (x *ClassListInput) ProtoReflect() protoreflect.Message {
	mi := &file_classes_class_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassListInput.ProtoReflect.Descriptor instead.
func (*ClassListInput) Descriptor() ([]byte, []int) {
	return file_classes_class_message_proto_rawDescGZIP(), []int{2}
}

func (x *ClassListInput) GetPagination() *generic.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ClassInput struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UniversityId   string                 `protobuf:"bytes,1,opt,name=university_id,json=universityId,proto3" json:"university_id,omitempty"`
	UniversityName string                 `protobuf:"bytes,2,opt,name=university_name,json=universityName,proto3" json:"university_name,omitempty"`
	FacultyId      string                 `protobuf:"bytes,3,opt,name=faculty_id,json=facultyId,proto3" json:"faculty_id,omitempty"`
	FacultyName    string                 `protobuf:"bytes,4,opt,name=faculty_name,json=facultyName,proto3" json:"faculty_name,omitempty"`
	ProgrammeId    string                 `protobuf:"bytes,5,opt,name=programme_id,json=programmeId,proto3" json:"programme_id,omitempty"`
	ProgrammeName  string                 `protobuf:"bytes,6,opt,name=programme_name,json=programmeName,proto3" json:"programme_name,omitempty"`
	Code           string                 `protobuf:"bytes,7,opt,name=code,proto3" json:"code,omitempty"`
	Name           string                 `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ClassInput) Reset() {
	*x = ClassInput{}
	mi := &file_classes_class_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassInput) ProtoMessage() {}

func (x *ClassInput) ProtoReflect() protoreflect.Message {
	mi := &file_classes_class_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassInput.ProtoReflect.Descriptor instead.
func (*ClassInput) Descriptor() ([]byte, []int) {
	return file_classes_class_message_proto_rawDescGZIP(), []int{3}
}

func (x *ClassInput) GetUniversityId() string {
	if x != nil {
		return x.UniversityId
	}
	return ""
}

func (x *ClassInput) GetUniversityName() string {
	if x != nil {
		return x.UniversityName
	}
	return ""
}

func (x *ClassInput) GetFacultyId() string {
	if x != nil {
		return x.FacultyId
	}
	return ""
}

func (x *ClassInput) GetFacultyName() string {
	if x != nil {
		return x.FacultyName
	}
	return ""
}

func (x *ClassInput) GetProgrammeId() string {
	if x != nil {
		return x.ProgrammeId
	}
	return ""
}

func (x *ClassInput) GetProgrammeName() string {
	if x != nil {
		return x.ProgrammeName
	}
	return ""
}

func (x *ClassInput) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ClassInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SubjectClass struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SubjectId     string                 `protobuf:"bytes,2,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	ClassId       string                 `protobuf:"bytes,3,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	Period        string                 `protobuf:"bytes,4,opt,name=period,proto3" json:"period,omitempty"`
	TeacherId     string                 `protobuf:"bytes,5,opt,name=teacher_id,json=teacherId,proto3" json:"teacher_id,omitempty"`
	TeacherName   string                 `protobuf:"bytes,6,opt,name=teacher_name,json=teacherName,proto3" json:"teacher_name,omitempty"`
	Name          string                 `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	TimetableDay  int32                  `protobuf:"varint,8,opt,name=timetable_day,json=timetableDay,proto3" json:"timetable_day,omitempty"`
	TimetableTime string                 `protobuf:"bytes,9,opt,name=timetable_time,json=timetableTime,proto3" json:"timetable_time,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,10,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubjectClass) Reset() {
	*x = SubjectClass{}
	mi := &file_classes_class_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubjectClass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubjectClass) ProtoMessage() {}

func (x *SubjectClass) ProtoReflect() protoreflect.Message {
	mi := &file_classes_class_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubjectClass.ProtoReflect.Descriptor instead.
func (*SubjectClass) Descriptor() ([]byte, []int) {
	return file_classes_class_message_proto_rawDescGZIP(), []int{4}
}

func (x *SubjectClass) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SubjectClass) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *SubjectClass) GetClassId() string {
	if x != nil {
		return x.ClassId
	}
	return ""
}

func (x *SubjectClass) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *SubjectClass) GetTeacherId() string {
	if x != nil {
		return x.TeacherId
	}
	return ""
}

func (x *SubjectClass) GetTeacherName() string {
	if x != nil {
		return x.TeacherName
	}
	return ""
}

func (x *SubjectClass) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SubjectClass) GetTimetableDay() int32 {
	if x != nil {
		return x.TimetableDay
	}
	return 0
}

func (x *SubjectClass) GetTimetableTime() string {
	if x != nil {
		return x.TimetableTime
	}
	return ""
}

func (x *SubjectClass) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *SubjectClass) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *SubjectClass) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type SubjectClassList struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubjectClasses []*SubjectClass        `protobuf:"bytes,1,rep,name=subject_classes,json=subjectClasses,proto3" json:"subject_classes,omitempty"`
	Count          uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubjectClassList) Reset() {
	*x = SubjectClassList{}
	mi := &file_classes_class_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubjectClassList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubjectClassList) ProtoMessage() {}

func (x *SubjectClassList) ProtoReflect() protoreflect.Message {
	mi := &file_classes_class_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubjectClassList.ProtoReflect.Descriptor instead.
func (*SubjectClassList) Descriptor() ([]byte, []int) {
	return file_classes_class_message_proto_rawDescGZIP(), []int{5}
}

func (x *SubjectClassList) GetSubjectClasses() []*SubjectClass {
	if x != nil {
		return x.SubjectClasses
	}
	return nil
}

func (x *SubjectClassList) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type SubjectClassListInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *generic.Pagination    `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	ClassId       string                 `protobuf:"bytes,2,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubjectClassListInput) Reset() {
	*x = SubjectClassListInput{}
	mi := &file_classes_class_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubjectClassListInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubjectClassListInput) ProtoMessage() {}

func (x *SubjectClassListInput) ProtoReflect() protoreflect.Message {
	mi := &file_classes_class_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubjectClassListInput.ProtoReflect.Descriptor instead.
func (*SubjectClassListInput) Descriptor() ([]byte, []int) {
	return file_classes_class_message_proto_rawDescGZIP(), []int{6}
}

func (x *SubjectClassListInput) GetPagination() *generic.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *SubjectClassListInput) GetClassId() string {
	if x != nil {
		return x.ClassId
	}
	return ""
}

type SubjectClassInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubjectId     string                 `protobuf:"bytes,1,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	ClassId       string                 `protobuf:"bytes,2,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	Period        string                 `protobuf:"bytes,3,opt,name=period,proto3" json:"period,omitempty"`
	TeacherId     string                 `protobuf:"bytes,4,opt,name=teacher_id,json=teacherId,proto3" json:"teacher_id,omitempty"`
	TeacherName   string                 `protobuf:"bytes,5,opt,name=teacher_name,json=teacherName,proto3" json:"teacher_name,omitempty"`
	Name          string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	TimetableDay  int32                  `protobuf:"varint,7,opt,name=timetable_day,json=timetableDay,proto3" json:"timetable_day,omitempty"`
	TimetableTime string                 `protobuf:"bytes,8,opt,name=timetable_time,json=timetableTime,proto3" json:"timetable_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubjectClassInput) Reset() {
	*x = SubjectClassInput{}
	mi := &file_classes_class_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubjectClassInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubjectClassInput) ProtoMessage() {}

func (x *SubjectClassInput) ProtoReflect() protoreflect.Message {
	mi := &file_classes_class_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubjectClassInput.ProtoReflect.Descriptor instead.
func (*SubjectClassInput) Descriptor() ([]byte, []int) {
	return file_classes_class_message_proto_rawDescGZIP(), []int{7}
}

func (x *SubjectClassInput) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *SubjectClassInput) GetClassId() string {
	if x != nil {
		return x.ClassId
	}
	return ""
}

func (x *SubjectClassInput) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *SubjectClassInput) GetTeacherId() string {
	if x != nil {
		return x.TeacherId
	}
	return ""
}

func (x *SubjectClassInput) GetTeacherName() string {
	if x != nil {
		return x.TeacherName
	}
	return ""
}

func (x *SubjectClassInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SubjectClassInput) GetTimetableDay() int32 {
	if x != nil {
		return x.TimetableDay
	}
	return 0
}

func (x *SubjectClassInput) GetTimetableTime() string {
	if x != nil {
		return x.TimetableTime
	}
	return ""
}

type StudentClass struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SubjectClassId string                 `protobuf:"bytes,2,opt,name=subject_class_id,json=subjectClassId,proto3" json:"subject_class_id,omitempty"`
	StudentId      string                 `protobuf:"bytes,3,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	StudentName    string                 `protobuf:"bytes,4,opt,name=student_name,json=studentName,proto3" json:"student_name,omitempty"`
	UpdatedBy      string                 `protobuf:"bytes,5,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StudentClass) Reset() {
	*x = StudentClass{}
	mi := &file_classes_class_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentClass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentClass) ProtoMessage() {}

func (x *StudentClass) ProtoReflect() protoreflect.Message {
	mi := &file_classes_class_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentClass.ProtoReflect.Descriptor instead.
func (*StudentClass) Descriptor() ([]byte, []int) {
	return file_classes_class_message_proto_rawDescGZIP(), []int{8}
}

func (x *StudentClass) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StudentClass) GetSubjectClassId() string {
	if x != nil {
		return x.SubjectClassId
	}
	return ""
}

func (x *StudentClass) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *StudentClass) GetStudentName() string {
	if x != nil {
		return x.StudentName
	}
	return ""
}

func (x *StudentClass) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *StudentClass) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *StudentClass) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type StudentClassList struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StudentClasses []*StudentClass        `protobuf:"bytes,1,rep,name=student_classes,json=studentClasses,proto3" json:"student_classes,omitempty"`
	Count          uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StudentClassList) Reset() {
	*x = StudentClassList{}
	mi := &file_classes_class_message_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentClassList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentClassList) ProtoMessage() {}

func (x *StudentClassList) ProtoReflect() protoreflect.Message {
	mi := &file_classes_class_message_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentClassList.ProtoReflect.Descriptor instead.
func (*StudentClassList) Descriptor() ([]byte, []int) {
	return file_classes_class_message_proto_rawDescGZIP(), []int{9}
}

func (x *StudentClassList) GetStudentClasses() []*StudentClass {
	if x != nil {
		return x.StudentClasses
	}
	return nil
}

func (x *StudentClassList) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type StudentClassListInput struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Pagination     *generic.Pagination    `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	SubjectClassId string                 `protobuf:"bytes,2,opt,name=subject_class_id,json=subjectClassId,proto3" json:"subject_class_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StudentClassListInput) Reset() {
	*x = StudentClassListInput{}
	mi := &file_classes_class_message_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentClassListInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentClassListInput) ProtoMessage() {}

func (x *StudentClassListInput) ProtoReflect() protoreflect.Message {
	mi := &file_classes_class_message_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentClassListInput.ProtoReflect.Descriptor instead.
func (*StudentClassListInput) Descriptor() ([]byte, []int) {
	return file_classes_class_message_proto_rawDescGZIP(), []int{10}
}

func (x *StudentClassListInput) GetPagination() *generic.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *StudentClassListInput) GetSubjectClassId() string {
	if x != nil {
		return x.SubjectClassId
	}
	return ""
}

type StudentClassInput struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubjectClassId string                 `protobuf:"bytes,1,opt,name=subject_class_id,json=subjectClassId,proto3" json:"subject_class_id,omitempty"`
	StudentId      string                 `protobuf:"bytes,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	StudentName    string                 `protobuf:"bytes,3,opt,name=student_name,json=studentName,proto3" json:"student_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StudentClassInput) Reset() {
	*x = StudentClassInput{}
	mi := &file_classes_class_message_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentClassInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentClassInput) ProtoMessage() {}

func (x *StudentClassInput) ProtoReflect() protoreflect.Message {
	mi := &file_classes_class_message_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentClassInput.ProtoReflect.Descriptor instead.
func (*StudentClassInput) Descriptor() ([]byte, []int) {
	return file_classes_class_message_proto_rawDescGZIP(), []int{11}
}

func (x *StudentClassInput) GetSubjectClassId() string {
	if x != nil {
		return x.SubjectClassId
	}
	return ""
}

func (x *StudentClassInput) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *StudentClassInput) GetStudentName() string {
	if x != nil {
		return x.StudentName
	}
	return ""
}

var File_classes_class_message_proto protoreflect.FileDescriptor

const file_classes_class_message_proto_rawDesc = "" +
	"\n" +
	"\x1bclasses/class_message.proto\x12\aclasses\x1a\x1dgeneric/generic_message.proto\"\xf6\x02\n" +
	"\x05Class\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\runiversity_id\x18\x02 \x01(\tR\funiversityId\x12'\n" +
	"\x0funiversity_name\x18\x03 \x01(\tR\x0euniversityName\x12\x1d\n" +
	"\n" +
	"faculty_id\x18\x04 \x01(\tR\tfacultyId\x12!\n" +
	"\ffaculty_name\x18\x05 \x01(\tR\vfacultyName\x12!\n" +
	"\fprogramme_id\x18\x06 \x01(\tR\vprogrammeId\x12%\n" +
	"\x0eprogramme_name\x18\a \x01(\tR\rprogrammeName\x12\x12\n" +
	"\x04code\x18\b \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\t \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"updated_by\x18\n" +
	" \x01(\tR\tupdatedBy\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\tR\tcreatedAt\"K\n" +
	"\tClassList\x12(\n" +
	"\aclasses\x18\x01 \x03(\v2\x0e.classes.ClassR\aclasses\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\"P\n" +
	"\x0eClassListInput\x12>\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x1e.lms_class_services.PaginationR\n" +
	"pagination\"\x8e\x02\n" +
	"\n" +
	"ClassInput\x12#\n" +
	"\runiversity_id\x18\x01 \x01(\tR\funiversityId\x12'\n" +
	"\x0funiversity_name\x18\x02 \x01(\tR\x0euniversityName\x12\x1d\n" +
	"\n" +
	"faculty_id\x18\x03 \x01(\tR\tfacultyId\x12!\n" +
	"\ffaculty_name\x18\x04 \x01(\tR\vfacultyName\x12!\n" +
	"\fprogramme_id\x18\x05 \x01(\tR\vprogrammeId\x12%\n" +
	"\x0eprogramme_name\x18\x06 \x01(\tR\rprogrammeName\x12\x12\n" +
	"\x04code\x18\a \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\b \x01(\tR\x04name\"\xef\x02\n" +
	"\fSubjectClass\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x02 \x01(\tR\tsubjectId\x12\x19\n" +
	"\bclass_id\x18\x03 \x01(\tR\aclassId\x12\x16\n" +
	"\x06period\x18\x04 \x01(\tR\x06period\x12\x1d\n" +
	"\n" +
	"teacher_id\x18\x05 \x01(\tR\tteacherId\x12!\n" +
	"\fteacher_name\x18\x06 \x01(\tR\vteacherName\x12\x12\n" +
	"\x04name\x18\a \x01(\tR\x04name\x12#\n" +
	"\rtimetable_day\x18\b \x01(\x05R\ftimetableDay\x12%\n" +
	"\x0etimetable_time\x18\t \x01(\tR\rtimetableTime\x12\x1d\n" +
	"\n" +
	"updated_by\x18\n" +
	" \x01(\tR\tupdatedBy\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\tR\tcreatedAt\"h\n" +
	"\x10SubjectClassList\x12>\n" +
	"\x0fsubject_classes\x18\x01 \x03(\v2\x15.classes.SubjectClassR\x0esubjectClasses\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\"r\n" +
	"\x15SubjectClassListInput\x12>\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x1e.lms_class_services.PaginationR\n" +
	"pagination\x12\x19\n" +
	"\bclass_id\x18\x02 \x01(\tR\aclassId\"\x87\x02\n" +
	"\x11SubjectClassInput\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x01 \x01(\tR\tsubjectId\x12\x19\n" +
	"\bclass_id\x18\x02 \x01(\tR\aclassId\x12\x16\n" +
	"\x06period\x18\x03 \x01(\tR\x06period\x12\x1d\n" +
	"\n" +
	"teacher_id\x18\x04 \x01(\tR\tteacherId\x12!\n" +
	"\fteacher_name\x18\x05 \x01(\tR\vteacherName\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12#\n" +
	"\rtimetable_day\x18\a \x01(\x05R\ftimetableDay\x12%\n" +
	"\x0etimetable_time\x18\b \x01(\tR\rtimetableTime\"\xe7\x01\n" +
	"\fStudentClass\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\x10subject_class_id\x18\x02 \x01(\tR\x0esubjectClassId\x12\x1d\n" +
	"\n" +
	"student_id\x18\x03 \x01(\tR\tstudentId\x12!\n" +
	"\fstudent_name\x18\x04 \x01(\tR\vstudentName\x12\x1d\n" +
	"\n" +
	"updated_by\x18\x05 \x01(\tR\tupdatedBy\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\"h\n" +
	"\x10StudentClassList\x12>\n" +
	"\x0fstudent_classes\x18\x01 \x03(\v2\x15.classes.StudentClassR\x0estudentClasses\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\"\x81\x01\n" +
	"\x15StudentClassListInput\x12>\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x1e.lms_class_services.PaginationR\n" +
	"pagination\x12(\n" +
	"\x10subject_class_id\x18\x02 \x01(\tR\x0esubjectClassId\"\x7f\n" +
	"\x11StudentClassInput\x12(\n" +
	"\x10subject_class_id\x18\x01 \x01(\tR\x0esubjectClassId\x12\x1d\n" +
	"\n" +
	"student_id\x18\x02 \x01(\tR\tstudentId\x12!\n" +
	"\fstudent_name\x18\x03 \x01(\tR\vstudentName2\x8e\x02\n" +
	"\fClassService\x123\n" +
	"\x04List\x12\x17.classes.ClassListInput\x1a\x12.classes.ClassList\x12-\n" +
	"\x03Get\x12\x16.lms_class_services.Id\x1a\x0e.classes.Class\x12-\n" +
	"\x06Create\x12\x13.classes.ClassInput\x1a\x0e.classes.Class\x12(\n" +
	"\x06Update\x12\x0e.classes.Class\x1a\x0e.classes.Class\x12A\n" +
	"\x06Delete\x12\x16.lms_class_services.Id\x1a\x1f.lms_class_services.BoolMessage2\xc6\x02\n" +
	"\x13SubjectClassService\x12A\n" +
	"\x04List\x12\x1e.classes.SubjectClassListInput\x1a\x19.classes.SubjectClassList\x124\n" +
	"\x03Get\x12\x16.lms_class_services.Id\x1a\x15.classes.SubjectClass\x12;\n" +
	"\x06Create\x12\x1a.classes.SubjectClassInput\x1a\x15.classes.SubjectClass\x126\n" +
	"\x06Update\x12\x15.classes.SubjectClass\x1a\x15.classes.SubjectClass\x12A\n" +
	"\x06Delete\x12\x16.lms_class_services.Id\x1a\x1f.lms_class_services.BoolMessage2\x8e\x02\n" +
	"\x13StudentClassService\x12A\n" +
	"\x04List\x12\x1e.classes.StudentClassListInput\x1a\x19.classes.StudentClassList\x124\n" +
	"\x03Get\x12\x16.lms_class_services.Id\x1a\x15.classes.StudentClass\x12;\n" +
	"\x06Create\x12\x1a.classes.StudentClassInput\x1a\x15.classes.StudentClass\x12A\n" +
	"\x06Delete\x12\x16.lms_class_services.Id\x1a\x1f.lms_class_services.BoolMessageB&Z$lms-class-service/pb/classes;classesb\x06proto3"

var (
	file_classes_class_message_proto_rawDescOnce sync.Once
	file_classes_class_message_proto_rawDescData []byte
)

func file_classes_class_message_proto_rawDescGZIP() []byte {
	file_classes_class_message_proto_rawDescOnce.Do(func() {
		file_classes_class_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_classes_class_message_proto_rawDesc), len(file_classes_class_message_proto_rawDesc)))
	})
	return file_classes_class_message_proto_rawDescData
}

var file_classes_class_message_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_classes_class_message_proto_goTypes = []any{
	(*Class)(nil),                 // 0: classes.Class
	(*ClassList)(nil),             // 1: classes.ClassList
	(*ClassListInput)(nil),        // 2: classes.ClassListInput
	(*ClassInput)(nil),            // 3: classes.ClassInput
	(*SubjectClass)(nil),          // 4: classes.SubjectClass
	(*SubjectClassList)(nil),      // 5: classes.SubjectClassList
	(*SubjectClassListInput)(nil), // 6: classes.SubjectClassListInput
	(*SubjectClassInput)(nil),     // 7: classes.SubjectClassInput
	(*StudentClass)(nil),          // 8: classes.StudentClass
	(*StudentClassList)(nil),      // 9: classes.StudentClassList
	(*StudentClassListInput)(nil), // 10: classes.StudentClassListInput
	(*StudentClassInput)(nil),     // 11: classes.StudentClassInput
	(*generic.Pagination)(nil),    // 12: lms_class_services.Pagination
	(*generic.Id)(nil),            // 13: lms_class_services.Id
	(*generic.BoolMessage)(nil),   // 14: lms_class_services.BoolMessage
}
var file_classes_class_message_proto_depIdxs = []int32{
	0,  // 0: classes.ClassList.classes:type_name -> classes.Class
	12, // 1: classes.ClassListInput.pagination:type_name -> lms_class_services.Pagination
	4,  // 2: classes.SubjectClassList.subject_classes:type_name -> classes.SubjectClass
	12, // 3: classes.SubjectClassListInput.pagination:type_name -> lms_class_services.Pagination
	8,  // 4: classes.StudentClassList.student_classes:type_name -> classes.StudentClass
	12, // 5: classes.StudentClassListInput.pagination:type_name -> lms_class_services.Pagination
	2,  // 6: classes.ClassService.List:input_type -> classes.ClassListInput
	13, // 7: classes.ClassService.Get:input_type -> lms_class_services.Id
	3,  // 8: classes.ClassService.Create:input_type -> classes.ClassInput
	0,  // 9: classes.ClassService.Update:input_type -> classes.Class
	13, // 10: classes.ClassService.Delete:input_type -> lms_class_services.Id
	6,  // 11: classes.SubjectClassService.List:input_type -> classes.SubjectClassListInput
	13, // 12: classes.SubjectClassService.Get:input_type -> lms_class_services.Id
	7,  // 13: classes.SubjectClassService.Create:input_type -> classes.SubjectClassInput
	4,  // 14: classes.SubjectClassService.Update:input_type -> classes.SubjectClass
	13, // 15: classes.SubjectClassService.Delete:input_type -> lms_class_services.Id
	10, // 16: classes.StudentClassService.List:input_type -> classes.StudentClassListInput
	13, // 17: classes.StudentClassService.Get:input_type -> lms_class_services.Id
	11, // 18: classes.StudentClassService.Create:input_type -> classes.StudentClassInput
	13, // 19: classes.StudentClassService.Delete:input_type -> lms_class_services.Id
	1,  // 20: classes.ClassService.List:output_type -> classes.ClassList
	0,  // 21: classes.ClassService.Get:output_type -> classes.Class
	0,  // 22: classes.ClassService.Create:output_type -> classes.Class
	0,  // 23: classes.ClassService.Update:output_type -> classes.Class
	14, // 24: classes.ClassService.Delete:output_type -> lms_class_services.BoolMessage
	5,  // 25: classes.SubjectClassService.List:output_type -> classes.SubjectClassList
	4,  // 26: classes.SubjectClassService.Get:output_type -> classes.SubjectClass
	4,  // 27: classes.SubjectClassService.Create:output_type -> classes.SubjectClass
	4,  // 28: classes.SubjectClassService.Update:output_type -> classes.SubjectClass
	14, // 29: classes.SubjectClassService.Delete:output_type -> lms_class_services.BoolMessage
	9,  // 30: classes.StudentClassService.List:output_type -> classes.StudentClassList
	8,  // 31: classes.StudentClassService.Get:output_type -> classes.StudentClass
	8,  // 32: classes.StudentClassService.Create:output_type -> classes.StudentClass
	14, // 33: classes.StudentClassService.Delete:output_type -> lms_class_services.BoolMessage
	20, // [20:34] is the sub-list for method output_type
	6,  // [6:20] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_classes_class_message_proto_init() }
func file_classes_class_message_proto_init() {
	if File_classes_class_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_classes_class_message_proto_rawDesc), len(file_classes_class_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_classes_class_message_proto_goTypes,
		DependencyIndexes: file_classes_class_message_proto_depIdxs,
		MessageInfos:      file_classes_class_message_proto_msgTypes,
	}.Build()
	File_classes_class_message_proto = out.File
	file_classes_class_message_proto_goTypes = nil
	file_classes_class_message_proto_depIdxs = nil
}
